# Generated by Django 2.2.1 on 2019-06-25 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='todo_dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'link')},
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_on', models.DateField()),
                ('completed_on', models.DateField(default=None)),
                ('completed', models.BooleanField(default=False)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.todo_dates')),
            ],
            options={
                'unique_together': {('content', 'created_on', 'completed_on', 'link')},
            },
        ),
    ]
