# Generated by Django 2.2.1 on 2019-06-25 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
