# Generated by Django 2.2.1 on 2019-06-25 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190625_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_dates',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
