# Generated by Django 2.2.1 on 2019-06-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190625_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='completed_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
