# Generated by Django 2.2.1 on 2019-06-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190625_2126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='items',
            unique_together={('content', 'link')},
        ),
    ]
