# Generated by Django 2.2.1 on 2019-06-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190625_2132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='items',
            unique_together={('content', 'link')},
        ),
    ]
